# Generated by Django 3.0.4 on 2020-03-19 17:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200319_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
