# Generated by Django 3.0.4 on 2020-03-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200319_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='country',
        ),
    ]
