# Generated by Django 3.0.4 on 2020-03-31 23:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2),
            preserve_default=False,
        ),
    ]
