# Generated by Django 3.0.4 on 2020-03-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment_commentreply_commentreport_donation_projectpicture_projectrating_projectreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrating',
            name='rating',
        ),
    ]
