# Generated by Django 3.0.4 on 2020-03-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='reply',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='total_target',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrating',
            name='rating',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
