# Generated by Django 3.0.4 on 2020-03-20 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20200316_1608'),
        ('projects', '0004_auto_20200318_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_registration.User'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_registration.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_registration.User'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_registration.User'),
        ),
    ]
