# Generated by Django 3.0.4 on 2020-03-23 22:39

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200320_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='pic_path',
            field=models.FileField(db_column='pic_path', upload_to=projects.models.get_upload_path_project_picture),
        ),
    ]
