# Generated by Django 3.0.4 on 2020-03-24 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20200316_1608'),
        ('projects', '0007_auto_20200323_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_registration.User'),
        ),
    ]
