# Generated by Django 3.0.4 on 2020-03-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('profile_pic', models.CharField(max_length=45)),
                ('is_activated', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('facebook_profile_id', models.CharField(max_length=45)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registration.Country')),
            ],
        ),
    ]
