# Generated by Django 3.0.4 on 2020-03-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_id',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_registration.Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_profile_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
